# Generated by Django 4.0.1 on 2022-01-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimage_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product/p1.png', upload_to='product/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
