# Generated by Django 4.0.1 on 2022-01-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image/p1.png', upload_to='image/'),
        ),
    ]
