# Generated by Django 4.0.1 on 2022-02-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='user_name',
        ),
    ]
