# Generated by Django 3.2.8 on 2022-02-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
